// Code generated by protoc-gen-go.
// source: proto/smartcentrix.proto
// DO NOT EDIT!

/*
Package smartcentrix is a generated protocol buffer package.

It is generated from these files:
	proto/smartcentrix.proto

It has these top-level messages:
	User
	Device
	Room
	Sensor
	Measurement
	RegisterUserRequest
	RegisterUserResponse
	RegisterSensorRequest
	RegisterSensorResponse
	UpdateSensorRequest
	UpdateSensorResponse
	ToggleSensorRequest
	ToggleSensorResponse
	ListSensorRequest
	ListSensorResponse
	ShowSensorRequest
	ShowSensorResponse
	DeleteSensorRequest
	DeleteSensorResponse
	ListSensorMeasurementRequest
	ListSensorMeasurementResponse
	UpdateSensorMeasurementRequest
	UpdateSensorMeasurementResponse
*/
package smartcentrix

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device_Type int32

const (
	Device_UNKNOWN Device_Type = 0
	Device_IOS     Device_Type = 1
	Device_ANDROID Device_Type = 2
)

var Device_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "IOS",
	2: "ANDROID",
}
var Device_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"IOS":     1,
	"ANDROID": 2,
}

func (x Device_Type) String() string {
	return proto.EnumName(Device_Type_name, int32(x))
}
func (Device_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type User struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Device struct {
	Id        string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type      Device_Type `protobuf:"varint,2,opt,name=type,enum=Device_Type" json:"type,omitempty"`
	PushToken string      `protobuf:"bytes,3,opt,name=push_token,json=pushToken" json:"push_token,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetType() Device_Type {
	if m != nil {
		return m.Type
	}
	return Device_UNKNOWN
}

func (m *Device) GetPushToken() string {
	if m != nil {
		return m.PushToken
	}
	return ""
}

type Room struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Sensor struct {
	Id              string                        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name            string                        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	LastMeasurement int64                         `protobuf:"varint,3,opt,name=last_measurement,json=lastMeasurement" json:"last_measurement,omitempty"`
	Status          bool                          `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	RoomId          *google_protobuf1.StringValue `protobuf:"bytes,5,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *Sensor) Reset()                    { *m = Sensor{} }
func (m *Sensor) String() string            { return proto.CompactTextString(m) }
func (*Sensor) ProtoMessage()               {}
func (*Sensor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Sensor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sensor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sensor) GetLastMeasurement() int64 {
	if m != nil {
		return m.LastMeasurement
	}
	return 0
}

func (m *Sensor) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Sensor) GetRoomId() *google_protobuf1.StringValue {
	if m != nil {
		return m.RoomId
	}
	return nil
}

type Measurement struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Value     int64  `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *Measurement) Reset()                    { *m = Measurement{} }
func (m *Measurement) String() string            { return proto.CompactTextString(m) }
func (*Measurement) ProtoMessage()               {}
func (*Measurement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Measurement) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Measurement) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Measurement) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type RegisterUserRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterUserRequest) Reset()                    { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()               {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RegisterUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterUserResponse struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *RegisterUserResponse) Reset()                    { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()               {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RegisterUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RegisterUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterSensorRequest struct {
	UserId   string                        `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SensorId string                        `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
	Name     *google_protobuf1.StringValue `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	RoomId   *google_protobuf1.StringValue `protobuf:"bytes,4,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *RegisterSensorRequest) Reset()                    { *m = RegisterSensorRequest{} }
func (m *RegisterSensorRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterSensorRequest) ProtoMessage()               {}
func (*RegisterSensorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RegisterSensorRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterSensorRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

func (m *RegisterSensorRequest) GetName() *google_protobuf1.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RegisterSensorRequest) GetRoomId() *google_protobuf1.StringValue {
	if m != nil {
		return m.RoomId
	}
	return nil
}

type RegisterSensorResponse struct {
	Sensor *Sensor `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
}

func (m *RegisterSensorResponse) Reset()                    { *m = RegisterSensorResponse{} }
func (m *RegisterSensorResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterSensorResponse) ProtoMessage()               {}
func (*RegisterSensorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RegisterSensorResponse) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

type UpdateSensorRequest struct {
	UserId   string                        `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SensorId string                        `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
	Name     *google_protobuf1.StringValue `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	RoomId   *google_protobuf1.StringValue `protobuf:"bytes,4,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Status   *google_protobuf1.BoolValue   `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateSensorRequest) Reset()                    { *m = UpdateSensorRequest{} }
func (m *UpdateSensorRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateSensorRequest) ProtoMessage()               {}
func (*UpdateSensorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateSensorRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateSensorRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

func (m *UpdateSensorRequest) GetName() *google_protobuf1.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UpdateSensorRequest) GetRoomId() *google_protobuf1.StringValue {
	if m != nil {
		return m.RoomId
	}
	return nil
}

func (m *UpdateSensorRequest) GetStatus() *google_protobuf1.BoolValue {
	if m != nil {
		return m.Status
	}
	return nil
}

type UpdateSensorResponse struct {
	Sensor *Sensor `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
}

func (m *UpdateSensorResponse) Reset()                    { *m = UpdateSensorResponse{} }
func (m *UpdateSensorResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateSensorResponse) ProtoMessage()               {}
func (*UpdateSensorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateSensorResponse) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

type ToggleSensorRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SensorId string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
	Status   bool   `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
}

func (m *ToggleSensorRequest) Reset()                    { *m = ToggleSensorRequest{} }
func (m *ToggleSensorRequest) String() string            { return proto.CompactTextString(m) }
func (*ToggleSensorRequest) ProtoMessage()               {}
func (*ToggleSensorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ToggleSensorRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ToggleSensorRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

func (m *ToggleSensorRequest) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ToggleSensorResponse struct {
	Sensor *Sensor `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
}

func (m *ToggleSensorResponse) Reset()                    { *m = ToggleSensorResponse{} }
func (m *ToggleSensorResponse) String() string            { return proto.CompactTextString(m) }
func (*ToggleSensorResponse) ProtoMessage()               {}
func (*ToggleSensorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ToggleSensorResponse) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

type ListSensorRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *ListSensorRequest) Reset()                    { *m = ListSensorRequest{} }
func (m *ListSensorRequest) String() string            { return proto.CompactTextString(m) }
func (*ListSensorRequest) ProtoMessage()               {}
func (*ListSensorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListSensorRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListSensorResponse struct {
	Sensors []*Sensor `protobuf:"bytes,1,rep,name=sensors" json:"sensors,omitempty"`
	Rooms   []*Room   `protobuf:"bytes,2,rep,name=rooms" json:"rooms,omitempty"`
}

func (m *ListSensorResponse) Reset()                    { *m = ListSensorResponse{} }
func (m *ListSensorResponse) String() string            { return proto.CompactTextString(m) }
func (*ListSensorResponse) ProtoMessage()               {}
func (*ListSensorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ListSensorResponse) GetSensors() []*Sensor {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *ListSensorResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type ShowSensorRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SensorId string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
}

func (m *ShowSensorRequest) Reset()                    { *m = ShowSensorRequest{} }
func (m *ShowSensorRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowSensorRequest) ProtoMessage()               {}
func (*ShowSensorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ShowSensorRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ShowSensorRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

type ShowSensorResponse struct {
	Sensor       *Sensor        `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
	Measurements []*Measurement `protobuf:"bytes,2,rep,name=measurements" json:"measurements,omitempty"`
}

func (m *ShowSensorResponse) Reset()                    { *m = ShowSensorResponse{} }
func (m *ShowSensorResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowSensorResponse) ProtoMessage()               {}
func (*ShowSensorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ShowSensorResponse) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *ShowSensorResponse) GetMeasurements() []*Measurement {
	if m != nil {
		return m.Measurements
	}
	return nil
}

type DeleteSensorRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SensorId string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
}

func (m *DeleteSensorRequest) Reset()                    { *m = DeleteSensorRequest{} }
func (m *DeleteSensorRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSensorRequest) ProtoMessage()               {}
func (*DeleteSensorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeleteSensorRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteSensorRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

type DeleteSensorResponse struct {
	Sensor       *Sensor        `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
	Measurements []*Measurement `protobuf:"bytes,2,rep,name=measurements" json:"measurements,omitempty"`
}

func (m *DeleteSensorResponse) Reset()                    { *m = DeleteSensorResponse{} }
func (m *DeleteSensorResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteSensorResponse) ProtoMessage()               {}
func (*DeleteSensorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DeleteSensorResponse) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *DeleteSensorResponse) GetMeasurements() []*Measurement {
	if m != nil {
		return m.Measurements
	}
	return nil
}

type ListSensorMeasurementRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SensorId string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
}

func (m *ListSensorMeasurementRequest) Reset()                    { *m = ListSensorMeasurementRequest{} }
func (m *ListSensorMeasurementRequest) String() string            { return proto.CompactTextString(m) }
func (*ListSensorMeasurementRequest) ProtoMessage()               {}
func (*ListSensorMeasurementRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ListSensorMeasurementRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListSensorMeasurementRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

type ListSensorMeasurementResponse struct {
	Measurements []*Measurement `protobuf:"bytes,1,rep,name=measurements" json:"measurements,omitempty"`
}

func (m *ListSensorMeasurementResponse) Reset()                    { *m = ListSensorMeasurementResponse{} }
func (m *ListSensorMeasurementResponse) String() string            { return proto.CompactTextString(m) }
func (*ListSensorMeasurementResponse) ProtoMessage()               {}
func (*ListSensorMeasurementResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ListSensorMeasurementResponse) GetMeasurements() []*Measurement {
	if m != nil {
		return m.Measurements
	}
	return nil
}

type UpdateSensorMeasurementRequest struct {
	UserId       string         `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SensorId     string         `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId" json:"sensor_id,omitempty"`
	Measurements []*Measurement `protobuf:"bytes,3,rep,name=measurements" json:"measurements,omitempty"`
}

func (m *UpdateSensorMeasurementRequest) Reset()                    { *m = UpdateSensorMeasurementRequest{} }
func (m *UpdateSensorMeasurementRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateSensorMeasurementRequest) ProtoMessage()               {}
func (*UpdateSensorMeasurementRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *UpdateSensorMeasurementRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateSensorMeasurementRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

func (m *UpdateSensorMeasurementRequest) GetMeasurements() []*Measurement {
	if m != nil {
		return m.Measurements
	}
	return nil
}

type UpdateSensorMeasurementResponse struct {
}

func (m *UpdateSensorMeasurementResponse) Reset()         { *m = UpdateSensorMeasurementResponse{} }
func (m *UpdateSensorMeasurementResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSensorMeasurementResponse) ProtoMessage()    {}
func (*UpdateSensorMeasurementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{22}
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*Room)(nil), "Room")
	proto.RegisterType((*Sensor)(nil), "Sensor")
	proto.RegisterType((*Measurement)(nil), "Measurement")
	proto.RegisterType((*RegisterUserRequest)(nil), "RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "RegisterUserResponse")
	proto.RegisterType((*RegisterSensorRequest)(nil), "RegisterSensorRequest")
	proto.RegisterType((*RegisterSensorResponse)(nil), "RegisterSensorResponse")
	proto.RegisterType((*UpdateSensorRequest)(nil), "UpdateSensorRequest")
	proto.RegisterType((*UpdateSensorResponse)(nil), "UpdateSensorResponse")
	proto.RegisterType((*ToggleSensorRequest)(nil), "ToggleSensorRequest")
	proto.RegisterType((*ToggleSensorResponse)(nil), "ToggleSensorResponse")
	proto.RegisterType((*ListSensorRequest)(nil), "ListSensorRequest")
	proto.RegisterType((*ListSensorResponse)(nil), "ListSensorResponse")
	proto.RegisterType((*ShowSensorRequest)(nil), "ShowSensorRequest")
	proto.RegisterType((*ShowSensorResponse)(nil), "ShowSensorResponse")
	proto.RegisterType((*DeleteSensorRequest)(nil), "DeleteSensorRequest")
	proto.RegisterType((*DeleteSensorResponse)(nil), "DeleteSensorResponse")
	proto.RegisterType((*ListSensorMeasurementRequest)(nil), "ListSensorMeasurementRequest")
	proto.RegisterType((*ListSensorMeasurementResponse)(nil), "ListSensorMeasurementResponse")
	proto.RegisterType((*UpdateSensorMeasurementRequest)(nil), "UpdateSensorMeasurementRequest")
	proto.RegisterType((*UpdateSensorMeasurementResponse)(nil), "UpdateSensorMeasurementResponse")
	proto.RegisterEnum("Device_Type", Device_Type_name, Device_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SensorApiService service

type SensorApiServiceClient interface {
	// RegisterUser registers a new user if no user with the same name exists
	//
	// The method returns the new user and an access token for future requests
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	// LoginUser tries to validate a username and password combination
	//
	// The method returns the existing user and an access token for future requests
	LoginUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	// RegisterSensor links a sensor a user if it's not yet linked to another user
	//
	// The method returns the newly registered sensor
	RegisterSensor(ctx context.Context, in *RegisterSensorRequest, opts ...grpc.CallOption) (*RegisterSensorResponse, error)
	// UpdateSensor updates a sensors name, status and assosiated room
	//
	// The method returns the newly registered sensor
	UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*UpdateSensorResponse, error)
	ToggleSensor(ctx context.Context, in *ToggleSensorRequest, opts ...grpc.CallOption) (*ToggleSensorResponse, error)
	ListSensor(ctx context.Context, in *ListSensorRequest, opts ...grpc.CallOption) (*ListSensorResponse, error)
	ShowSensor(ctx context.Context, in *ShowSensorRequest, opts ...grpc.CallOption) (*ShowSensorResponse, error)
	DeleteSensor(ctx context.Context, in *DeleteSensorRequest, opts ...grpc.CallOption) (*DeleteSensorResponse, error)
	ListSensorMeasurement(ctx context.Context, in *ListSensorMeasurementRequest, opts ...grpc.CallOption) (*ListSensorMeasurementResponse, error)
	UpdateSensorMeasurement(ctx context.Context, in *UpdateSensorMeasurementRequest, opts ...grpc.CallOption) (*UpdateSensorMeasurementResponse, error)
}

type sensorApiServiceClient struct {
	cc *grpc.ClientConn
}

func NewSensorApiServiceClient(cc *grpc.ClientConn) SensorApiServiceClient {
	return &sensorApiServiceClient{cc}
}

func (c *sensorApiServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/RegisterUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) LoginUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/LoginUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) RegisterSensor(ctx context.Context, in *RegisterSensorRequest, opts ...grpc.CallOption) (*RegisterSensorResponse, error) {
	out := new(RegisterSensorResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/RegisterSensor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*UpdateSensorResponse, error) {
	out := new(UpdateSensorResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/UpdateSensor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) ToggleSensor(ctx context.Context, in *ToggleSensorRequest, opts ...grpc.CallOption) (*ToggleSensorResponse, error) {
	out := new(ToggleSensorResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/ToggleSensor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) ListSensor(ctx context.Context, in *ListSensorRequest, opts ...grpc.CallOption) (*ListSensorResponse, error) {
	out := new(ListSensorResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/ListSensor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) ShowSensor(ctx context.Context, in *ShowSensorRequest, opts ...grpc.CallOption) (*ShowSensorResponse, error) {
	out := new(ShowSensorResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/ShowSensor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) DeleteSensor(ctx context.Context, in *DeleteSensorRequest, opts ...grpc.CallOption) (*DeleteSensorResponse, error) {
	out := new(DeleteSensorResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/DeleteSensor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) ListSensorMeasurement(ctx context.Context, in *ListSensorMeasurementRequest, opts ...grpc.CallOption) (*ListSensorMeasurementResponse, error) {
	out := new(ListSensorMeasurementResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/ListSensorMeasurement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorApiServiceClient) UpdateSensorMeasurement(ctx context.Context, in *UpdateSensorMeasurementRequest, opts ...grpc.CallOption) (*UpdateSensorMeasurementResponse, error) {
	out := new(UpdateSensorMeasurementResponse)
	err := grpc.Invoke(ctx, "/SensorApiService/UpdateSensorMeasurement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SensorApiService service

type SensorApiServiceServer interface {
	// RegisterUser registers a new user if no user with the same name exists
	//
	// The method returns the new user and an access token for future requests
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	// LoginUser tries to validate a username and password combination
	//
	// The method returns the existing user and an access token for future requests
	LoginUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	// RegisterSensor links a sensor a user if it's not yet linked to another user
	//
	// The method returns the newly registered sensor
	RegisterSensor(context.Context, *RegisterSensorRequest) (*RegisterSensorResponse, error)
	// UpdateSensor updates a sensors name, status and assosiated room
	//
	// The method returns the newly registered sensor
	UpdateSensor(context.Context, *UpdateSensorRequest) (*UpdateSensorResponse, error)
	ToggleSensor(context.Context, *ToggleSensorRequest) (*ToggleSensorResponse, error)
	ListSensor(context.Context, *ListSensorRequest) (*ListSensorResponse, error)
	ShowSensor(context.Context, *ShowSensorRequest) (*ShowSensorResponse, error)
	DeleteSensor(context.Context, *DeleteSensorRequest) (*DeleteSensorResponse, error)
	ListSensorMeasurement(context.Context, *ListSensorMeasurementRequest) (*ListSensorMeasurementResponse, error)
	UpdateSensorMeasurement(context.Context, *UpdateSensorMeasurementRequest) (*UpdateSensorMeasurementResponse, error)
}

func RegisterSensorApiServiceServer(s *grpc.Server, srv SensorApiServiceServer) {
	s.RegisterService(&_SensorApiService_serviceDesc, srv)
}

func _SensorApiService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).LoginUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_RegisterSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).RegisterSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/RegisterSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).RegisterSensor(ctx, req.(*RegisterSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_UpdateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).UpdateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/UpdateSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).UpdateSensor(ctx, req.(*UpdateSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_ToggleSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).ToggleSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/ToggleSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).ToggleSensor(ctx, req.(*ToggleSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_ListSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).ListSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/ListSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).ListSensor(ctx, req.(*ListSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_ShowSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).ShowSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/ShowSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).ShowSensor(ctx, req.(*ShowSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_DeleteSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).DeleteSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/DeleteSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).DeleteSensor(ctx, req.(*DeleteSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_ListSensorMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSensorMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).ListSensorMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/ListSensorMeasurement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).ListSensorMeasurement(ctx, req.(*ListSensorMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorApiService_UpdateSensorMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSensorMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorApiServiceServer).UpdateSensorMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorApiService/UpdateSensorMeasurement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorApiServiceServer).UpdateSensorMeasurement(ctx, req.(*UpdateSensorMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SensorApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SensorApiService",
	HandlerType: (*SensorApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _SensorApiService_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _SensorApiService_LoginUser_Handler,
		},
		{
			MethodName: "RegisterSensor",
			Handler:    _SensorApiService_RegisterSensor_Handler,
		},
		{
			MethodName: "UpdateSensor",
			Handler:    _SensorApiService_UpdateSensor_Handler,
		},
		{
			MethodName: "ToggleSensor",
			Handler:    _SensorApiService_ToggleSensor_Handler,
		},
		{
			MethodName: "ListSensor",
			Handler:    _SensorApiService_ListSensor_Handler,
		},
		{
			MethodName: "ShowSensor",
			Handler:    _SensorApiService_ShowSensor_Handler,
		},
		{
			MethodName: "DeleteSensor",
			Handler:    _SensorApiService_DeleteSensor_Handler,
		},
		{
			MethodName: "ListSensorMeasurement",
			Handler:    _SensorApiService_ListSensorMeasurement_Handler,
		},
		{
			MethodName: "UpdateSensorMeasurement",
			Handler:    _SensorApiService_UpdateSensorMeasurement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/smartcentrix.proto",
}

func init() { proto.RegisterFile("proto/smartcentrix.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 997 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0x66, 0x6c, 0xc7, 0x8e, 0x2b, 0x56, 0x70, 0xca, 0x76, 0xe2, 0x4c, 0x9c, 0xc4, 0x69, 0x09,
	0x91, 0xb5, 0x96, 0x76, 0xe2, 0x15, 0xac, 0x76, 0xc5, 0x65, 0x51, 0x10, 0xb2, 0x76, 0x49, 0xb4,
	0x63, 0x87, 0x9f, 0x53, 0x34, 0x1b, 0x37, 0xde, 0x01, 0x7b, 0x7a, 0x98, 0x6e, 0x27, 0xac, 0x56,
	0x7b, 0x41, 0x1c, 0xb8, 0x22, 0x6e, 0x3c, 0x00, 0x8f, 0xc0, 0x8b, 0xf0, 0x0a, 0x1c, 0x78, 0x02,
	0xce, 0xa8, 0x7b, 0xc6, 0xf6, 0x38, 0x1e, 0x27, 0x13, 0x11, 0x0e, 0x7b, 0x73, 0x57, 0xd5, 0x7c,
	0xf5, 0x55, 0x55, 0xf7, 0x57, 0x86, 0xaa, 0xe7, 0x73, 0xc9, 0x9b, 0x62, 0x68, 0xfb, 0xf2, 0x9c,
	0xb9, 0xd2, 0x77, 0x7e, 0xa0, 0xda, 0x64, 0xd6, 0xfa, 0x9c, 0xf7, 0x07, 0xac, 0x69, 0x7b, 0x4e,
	0xd3, 0x76, 0x5d, 0x2e, 0x6d, 0xe9, 0x70, 0x57, 0x84, 0xde, 0x9d, 0xd0, 0xab, 0x4f, 0x2f, 0x46,
	0xdf, 0x34, 0x2f, 0x7d, 0xdb, 0xf3, 0x98, 0x1f, 0xfa, 0x49, 0x03, 0x32, 0xa7, 0x82, 0xf9, 0xb8,
	0x0a, 0x29, 0xa7, 0x57, 0x35, 0xea, 0xc6, 0x7e, 0xde, 0x4a, 0x39, 0x3d, 0x44, 0xc8, 0xb8, 0xf6,
	0x90, 0x55, 0x53, 0xda, 0xa2, 0x7f, 0x93, 0x9f, 0x0c, 0xc8, 0x1e, 0xb1, 0x0b, 0xe7, 0x9c, 0xcd,
	0x85, 0xd7, 0x21, 0x23, 0x5f, 0x79, 0x41, 0xf8, 0x6a, 0xab, 0x40, 0x83, 0x30, 0xda, 0x7d, 0xe5,
	0x31, 0x4b, 0x7b, 0x70, 0x1b, 0xc0, 0x1b, 0x89, 0x97, 0x67, 0x92, 0x7f, 0xc7, 0xdc, 0x6a, 0x5a,
	0x7f, 0x99, 0x57, 0x96, 0xae, 0x32, 0x90, 0x7b, 0x90, 0x51, 0xc1, 0xb8, 0x02, 0xb9, 0xd3, 0xe3,
	0xa7, 0xc7, 0x27, 0x5f, 0x1e, 0x17, 0xdf, 0xc1, 0x1c, 0xa4, 0xdb, 0x27, 0x9d, 0xa2, 0xa1, 0xac,
	0x4f, 0x8e, 0x8f, 0xac, 0x93, 0xf6, 0x51, 0x31, 0xa5, 0x28, 0x5b, 0x9c, 0x0f, 0x13, 0x51, 0xfe,
	0xdd, 0x80, 0x6c, 0x87, 0xb9, 0x82, 0x27, 0xaa, 0x10, 0xef, 0x41, 0x71, 0x60, 0x0b, 0x79, 0x36,
	0x64, 0xb6, 0x18, 0xf9, 0x6c, 0xc8, 0x5c, 0xa9, 0xa9, 0xa6, 0xad, 0x77, 0x95, 0xfd, 0xf3, 0xa9,
	0x19, 0xd7, 0x21, 0x2b, 0xa4, 0x2d, 0x47, 0xa2, 0x9a, 0xa9, 0x1b, 0xfb, 0xcb, 0x56, 0x78, 0xc2,
	0x0f, 0x21, 0xe7, 0x73, 0x3e, 0x3c, 0x73, 0x7a, 0xd5, 0xa5, 0xba, 0xb1, 0xbf, 0xd2, 0xaa, 0xd1,
	0x60, 0x04, 0x74, 0x3c, 0x02, 0xda, 0x91, 0xbe, 0xe3, 0xf6, 0xbf, 0xb0, 0x07, 0x23, 0x66, 0x65,
	0x55, 0x70, 0xbb, 0x47, 0x9e, 0xc3, 0x4a, 0x14, 0xfd, 0x2a, 0xd9, 0x1a, 0xe4, 0xa5, 0x33, 0x64,
	0x42, 0xda, 0x43, 0x4f, 0x33, 0x4e, 0x5b, 0x53, 0x03, 0x96, 0x61, 0xe9, 0x42, 0xa1, 0x85, 0x5c,
	0x83, 0x03, 0xf9, 0x14, 0x4a, 0x16, 0xeb, 0x3b, 0x42, 0x32, 0x5f, 0x8d, 0xd8, 0x62, 0xdf, 0x8f,
	0x98, 0x90, 0x93, 0xba, 0x8d, 0x48, 0xdd, 0x26, 0x2c, 0x7b, 0xb6, 0x10, 0x97, 0xdc, 0xef, 0x85,
	0xfd, 0x98, 0x9c, 0xc9, 0x67, 0x50, 0x9e, 0x85, 0x11, 0x1e, 0x77, 0x05, 0xc3, 0x4d, 0xc8, 0x8c,
	0x04, 0xf3, 0x35, 0xce, 0x4a, 0x6b, 0x89, 0x6a, 0xa7, 0x36, 0x29, 0x3e, 0xc1, 0x98, 0x03, 0xac,
	0xe0, 0x40, 0xfe, 0x30, 0xa0, 0x32, 0x46, 0x0a, 0x66, 0x32, 0xa6, 0xb4, 0x01, 0x39, 0xf5, 0xdd,
	0xd9, 0xa4, 0xe4, 0xac, 0x3a, 0xb6, 0x7b, 0xb8, 0x05, 0x79, 0xa1, 0x23, 0x95, 0x2b, 0x24, 0x16,
	0x18, 0xda, 0x3d, 0x3c, 0x08, 0x0b, 0x49, 0x27, 0x68, 0x73, 0x50, 0x66, 0x64, 0x36, 0x99, 0x5b,
	0xcc, 0xe6, 0x11, 0xac, 0x5f, 0xe5, 0x1d, 0xf6, 0x60, 0x17, 0xb2, 0x01, 0x9d, 0xb0, 0x0b, 0x39,
	0x1a, 0x06, 0x84, 0x66, 0xf2, 0xb7, 0x01, 0xa5, 0x53, 0xaf, 0x67, 0x4b, 0xf6, 0x36, 0x55, 0x8c,
	0xad, 0xc9, 0xe5, 0x0e, 0xee, 0xb0, 0x39, 0xf7, 0xd5, 0x27, 0x9c, 0x0f, 0xc2, 0x6f, 0x82, 0x48,
	0xf2, 0x10, 0xca, 0xb3, 0x95, 0x26, 0xed, 0xd1, 0x39, 0x94, 0xba, 0xbc, 0xdf, 0x1f, 0xdc, 0x49,
	0x8b, 0xa6, 0xcf, 0x32, 0x1d, 0x7d, 0x96, 0x8a, 0xdd, 0x6c, 0x92, 0xa4, 0xec, 0xee, 0xc3, 0xda,
	0x33, 0x47, 0xc8, 0x64, 0xdc, 0x48, 0x17, 0x30, 0x1a, 0x1d, 0x26, 0xd9, 0x83, 0x5c, 0x80, 0x26,
	0xaa, 0x46, 0x3d, 0x1d, 0xcd, 0x32, 0xb6, 0xe3, 0x16, 0x2c, 0xa9, 0xde, 0x8b, 0x6a, 0x4a, 0x07,
	0x2c, 0x51, 0x25, 0x71, 0x56, 0x60, 0x23, 0x6d, 0x58, 0xeb, 0xbc, 0xe4, 0x97, 0x77, 0xd0, 0x1f,
	0xd2, 0x07, 0x8c, 0x42, 0x25, 0xec, 0x02, 0x1e, 0x40, 0x21, 0xa2, 0x89, 0x63, 0x96, 0x05, 0x1a,
	0xd1, 0x2c, 0x6b, 0x26, 0x82, 0x3c, 0x85, 0xd2, 0x11, 0x1b, 0xb0, 0x3b, 0xb9, 0xf8, 0xc4, 0x81,
	0xf2, 0x2c, 0xd8, 0xff, 0xc7, 0xbb, 0x0b, 0xb5, 0xe9, 0x04, 0xa3, 0x61, 0xff, 0xa9, 0x80, 0xe7,
	0xb0, 0xbd, 0x00, 0x35, 0xac, 0xe4, 0x2a, 0x51, 0xe3, 0x46, 0xa2, 0x3f, 0x1b, 0xb0, 0x13, 0x7d,
	0x70, 0x77, 0xc5, 0x75, 0x8e, 0x4a, 0xfa, 0x46, 0x2a, 0x7b, 0xb0, 0xbb, 0x90, 0x49, 0x50, 0x5f,
	0xeb, 0x9f, 0x65, 0x28, 0x06, 0xde, 0x27, 0x9e, 0xd3, 0x61, 0xbe, 0xfe, 0x17, 0xf1, 0x35, 0x14,
	0xa2, 0xab, 0x05, 0xcb, 0x34, 0x66, 0x61, 0x99, 0x15, 0x1a, 0xb7, 0x7f, 0x48, 0xed, 0xc7, 0x3f,
	0xff, 0xfa, 0x35, 0xb5, 0x4e, 0xd6, 0x9a, 0x17, 0x87, 0x4d, 0x55, 0x57, 0xd3, 0x0f, 0xc3, 0x1e,
	0x1b, 0x0d, 0xec, 0x40, 0xfe, 0x19, 0xef, 0x3b, 0xee, 0xed, 0x71, 0x37, 0x35, 0x6e, 0x89, 0xac,
	0x4e, 0x70, 0x07, 0x0a, 0x48, 0x81, 0x7a, 0xb0, 0x3a, 0xbb, 0x08, 0x70, 0x9d, 0xc6, 0x6e, 0x34,
	0x73, 0x83, 0xc6, 0x6f, 0x0c, 0xf2, 0x81, 0x46, 0x7f, 0x9f, 0x90, 0x09, 0xfa, 0xeb, 0x70, 0x44,
	0x6f, 0x9a, 0xc1, 0x04, 0x66, 0xca, 0x18, 0x42, 0x21, 0xda, 0x59, 0x2c, 0xd3, 0x98, 0x6d, 0x62,
	0x56, 0x68, 0x9c, 0xf2, 0x92, 0x03, 0x9d, 0xab, 0x41, 0xde, 0x5b, 0x9c, 0xeb, 0xf5, 0xe4, 0x1a,
	0xbc, 0x51, 0xe9, 0x24, 0x14, 0xa2, 0x2a, 0x89, 0x65, 0x1a, 0xa3, 0xcc, 0x66, 0x85, 0xc6, 0x49,
	0x29, 0x79, 0xa8, 0xd3, 0x1d, 0x92, 0xfb, 0x89, 0xd2, 0x35, 0xa5, 0xc6, 0x50, 0x59, 0xbf, 0x02,
	0x98, 0x3e, 0x0e, 0x44, 0x3a, 0xa7, 0xb7, 0x66, 0x89, 0xce, 0xab, 0x2a, 0xd9, 0xd3, 0xf9, 0xb6,
	0x70, 0x73, 0x61, 0x3e, 0xec, 0x01, 0x4c, 0xd5, 0x0e, 0x91, 0xce, 0xa9, 0xa8, 0x59, 0xa2, 0xf3,
	0x72, 0x38, 0x1e, 0x12, 0x26, 0x6b, 0x1c, 0x7e, 0x0b, 0x85, 0xa8, 0x3a, 0x61, 0x99, 0xc6, 0x28,
	0x9f, 0x59, 0xa1, 0x71, 0x12, 0x36, 0xce, 0xd5, 0x48, 0x98, 0xeb, 0x17, 0x03, 0x2a, 0xb1, 0x4a,
	0x82, 0xdb, 0xf4, 0x3a, 0xdd, 0x32, 0x77, 0xe8, 0xb5, 0x02, 0x44, 0x1e, 0x69, 0x1e, 0x0f, 0xf0,
	0x30, 0xd9, 0xf4, 0x22, 0xef, 0x1f, 0x7f, 0x33, 0x60, 0x63, 0xc1, 0xfb, 0xc7, 0x5d, 0x7a, 0xbd,
	0x46, 0x99, 0x75, 0x7a, 0x83, 0x74, 0x90, 0x8f, 0x35, 0xb3, 0x8f, 0xc8, 0xed, 0x99, 0x3d, 0x36,
	0x1a, 0x2f, 0xb2, 0xfa, 0x2f, 0xcb, 0x83, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x15, 0x77, 0x02,
	0x6b, 0x41, 0x0d, 0x00, 0x00,
}
